name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      # We install our dependencies
      - name: Run npm install
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
        run: npm ci --no-audit --no-progress --force --ignore-scripts

      # We launch our postinstall scripts
      - name: Run npm postinstall
        shell: bash
        run: |
          npm rebuild
          npm run install --if-present
          npm run prepare --if-present

      - name: Deploy to GitHub Pages
        env:
          USE_SSH: false
          GIT_USER: tractr-bot
          GIT_PASS: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "tractr-bot@tractr.net"
          git config --global user.name "tractr-bot"
          nx build docs
          nx deploy docs
